version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - node.name=master-node
      - node.master=true
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.initial_master_nodes=master-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks:
      - elastic
    stdin_open: true
    tty: true
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: elasticsearch2
    environment:
      - node.name=data-node1
      - node.master=false
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.initial_master_nodes=master-node"
    ports:
      - 127.0.0.1:9301:9301
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data02:/usr/share/elasticsearch/data
    networks:
      - elastic
    stdin_open: true
    tty: true

  logstash:
    container_name: logstash
    build: ./logstash
    image: logstash
    links:
      - elasticsearch
      - elasticsearch2
    volumes:
    - ./:/config-dir
    depends_on:
      - elasticsearch
      - elasticsearch2
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    container_name: kibana
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - logstash
      - elasticsearch2
      
  app:
    image: app
    container_name: app
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app/quotes
    links:
        - elasticsearch
        - elasticsearch2
    depends_on:
        - elasticsearch
        - elasticsearch2
    networks:
      - elastic

volumes:
  es-data01:
    driver: local
  es-data02:
    driver: local

networks:
  elastic:
   driver: bridge